# Generated by Django 3.2.5 on 2024-04-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srno', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('filter', models.CharField(choices=[('programming', 'programming'), ('cloud', 'cloud'), ('networking', 'networking'), ('other', 'other')], max_length=200)),
                ('pic', models.ImageField(blank=True, default='blank.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srno', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vlink', models.CharField(blank=True, max_length=200, null=True)),
                ('glink', models.CharField(blank=True, max_length=200, null=True)),
                ('pic', models.ImageField(blank=True, default='blank.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
